### ISSUE TITLE
Setup as monorepo

### ISSUE THREAD

**Issue by chrisdmacrae** [spike-js/spike#3]
## Struggle/Problem

When a project with a lot of complexity is built as a single unit, the edges become blurry. This can lead to code that is hard to test, hard to read, and hard to change.

## Solution

Breaking up the project into many private packages that come together at build time makes the purpose of each package clear, makes refactoring easier, and makes contributing easier.

A new contributor can find the package they need to change, and have confidence only the code in that package is the code they need to touch.

## Risks and Rabbit Holes

- Organization. Packages should be broken up my domain concepts, like:
  - Core Parser
  - Core Compiler
  - CLI
  - Node API
  - Executable

## Appetite

- 1 hour, 1 person

## Note

I see this structured as follows:

```
|- packages/
|-- @ekipse/ - all core code, sorted into sub-packages
|---- parser/
|------ package.json
|---- compiler/
|-- ekipse - the main package
|---- package.json
|-- ekipse-cli - the logic for the CLI
|---- package.json
|-- ekipse-executables - the logic for creating the executable
|---- package.json
|- CONTRIBUTING.md
|- eslintrc
|- lerna.json
|- package.json
|- README.md
```

Using lerna to handle it, with interactions via package.json `scripts` like:

```
# development mode
npm run start
npm run start -- --scope ekipse, ekipse-cli 

# production build
npm run build
npm run build -- --scope ekipse, ekipse-cli

# test
npm run test
npm run test -- --scope ekipse, ekipse-cli
```

**Comment by chrisdmacrae** [comment]
@jssee want to review?

**Comment by jssee** [comment]
@chrisdmacrae yeah this seems like a standard setup for this type of thing. 

I think we should loop jeff in sooner rather than later, it would save us some potential headaches down the road specifically when it comes to naming stuff.
