### ISSUE TITLE
Rename epikse org and repo to spike

### ISSUE THREAD

**Issue by jssee** [spike-js/spike#4]
## Struggle/Problem
Eventually this org will host the npm package `spike`, which will require an as of yet unknown amount of updates to the code that currently uses a codename.

## Solution
Lets rename the org and associated repos to adopt the `spike` namespace

## Risks and Rabbit Holes
Maybe in the end we decide not to use the spike name, but in either case we wouldnt be in the same position as if we didnt rename now

## Appetite
less than 1 hour for one person

## Note
we have jeffs blessing (in slack)

**Comment by jssee** [comment]
@chrisdmacrae feel free to comment, i think we should do this before handling #3 fwiw

**Comment by chrisdmacrae** [comment]
@jssee do it up! You’re an org owner.
